using System.Linq;
using Content.Client._ES.Core;
using Content.Client.Station;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Cargo.Requests;
using Content.Shared._ES.Cargo.Requests.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._ES.Cargo.Requests.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCargoRequestConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly StationSystem _station;

    public event Action<string>? OnDepartmentIdChanged;
    public event Action<string>? OnCreateRequest;
    public event Action<int, ESCargoRequestStatus>? OnStatusChanged;

    private ESRequestCreationWindow? _requestCreationWindow;

    public ESCargoRequestConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _station = _entityManager.System<StationSystem>();

        DepartmentIdButtonEdit.OnPressed += _ =>
        {
            IdDisplayContainer.Visible = false;
            IdEditContainer.Visible = true;

            DepartmentIdEdit.GrabKeyboardFocus();
        };

        DepartmentIdEdit.OnFocusExit += _ =>
        {
            OnDepartmentIdChanged?.Invoke(DepartmentIdEdit.Text);
            IdDisplayContainer.Visible = true;
            IdEditContainer.Visible = false;
        };
        DepartmentIdEdit.OnTextEntered += _ => DepartmentIdEdit.ReleaseKeyboardFocus();
        DepartmentIdEdit.IsValid = ESSharedCargoRequestSystem.ValidateDepartmentId;

        CreateRequestButton.OnPressed += _ =>
        {
            if (_requestCreationWindow != null)
                return;

            _requestCreationWindow = new ESRequestCreationWindow();
            _requestCreationWindow.OpenCenteredRight();
            OnClose += _requestCreationWindow.Close;

            _requestCreationWindow.OnRequestConfirm += OnCreateRequest;
            _requestCreationWindow.OnClose += () =>
            {
                _requestCreationWindow.OnRequestConfirm -= OnCreateRequest;
                _requestCreationWindow = null;
            };
        };
    }

    public void Update(EntityUid owner)
    {
        if (!_entityManager.TryGetComponent<ESCargoRequestConsoleComponent>(owner, out var comp))
            return;
        DepartmentIdLabel.UnsafeSetMarkup($"[font=\"Monospace\"]{FormattedMessage.RemoveMarkupPermissive(comp.ConsoleId)}[/font]");
        DepartmentIdEdit.Text = comp.ConsoleId;

        CreateRequestButton.Visible = !comp.MasterConsole;
        IdMetaContainer.Visible = !comp.MasterConsole;
        Title = comp.MasterConsole
            ? Loc.GetString("es-cargo-request-ui-title-master")
            : Loc.GetString("es-cargo-request-ui-title");

        UpdateRequests((owner, comp));
    }

    public void UpdateRequests(Entity<ESCargoRequestConsoleComponent> ent)
    {
        if (_station.GetOwningStation(ent) is not { } station ||
            !_entityManager.TryGetComponent<ESCargoRequestStationComponent>(station, out var comp))
            return;

        RequestsContainer.Children.Clear();

        var departmentId = ent.Comp.ConsoleId;
        var requests = comp.Requests
            .OrderBy(p => p.Value.Status)
            .ThenByDescending(p => p.Key);
        foreach (var (rid, request) in requests)
        {
            if (request.Department != departmentId && !ent.Comp.MasterConsole)
                continue;

            var entry = new ESRequestEntry(request, rid, ent.Comp.MasterConsole);
            entry.OnStatusChanged += (i, status) => { OnStatusChanged?.Invoke(i, status); };
            RequestsContainer.AddChild(entry);
        }

        NoRequestsLabel.Visible = !RequestsContainer.Children.Any();
    }
}

