using Content.Client.Message;
using Content.Shared._ES.Cargo.Requests;
using Content.Shared._ES.Cargo.Requests.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._ES.Cargo.Requests.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESRequestEntry : BoxContainer
{
    public event Action<int, ESCargoRequestStatus>? OnStatusChanged;

    public ESRequestEntry(ESCargoRequest request, int rid, bool master)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ManifestLabel.SetMarkup(Loc.GetString("es-cargo-request-ui-entry-label-department", ("name", request.Department)));
        RewardLabel.SetMarkup(Loc.GetString("es-cargo-request-ui-entry-label-requester", ("name", request.User)));
        DescriptionLabel.SetMarkup(Loc.GetString("es-cargo-request-ui-entry-label-body", ("text", FormattedMessage.RemoveMarkupPermissive(request.RequestBody))));
        IdLabel.SetMarkup(Loc.GetString("es-cargo-request-ui-entry-label-id", ("name", rid)));

        StatusOption.Disabled = !master;
        foreach (var status in Enum.GetValues<ESCargoRequestStatus>())
        {
            StatusOption.AddItem(Loc.GetString(ESSharedCargoRequestSystem.GetLocalizedText(status)), (int) status);
            if (status == request.Status)
                StatusOption.SelectId((int) status);
        }

        StatusOption.OnItemSelected += args =>
        {
            StatusOption.SelectId(args.Id);
            OnStatusChanged?.Invoke(rid, (ESCargoRequestStatus) args.Id);
        };

        Modulate = request.Status switch
        {
            ESCargoRequestStatus.Denied => Color.Red,
            ESCargoRequestStatus.Completed => Color.Green,
            ESCargoRequestStatus.Cancelled => Color.DarkGray,
            _ => Color.White,
        };
    }
}
