using Content.Client._ES.Core;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Telesci.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Telesci.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESPortalGeneratorConsoleWindow : FancyWindow
{
    public event Action? OnActivatePressed;

    public ESPortalGeneratorConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ChargeBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.Yellow);
        ResearchBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.Magenta);

        ActivateButton.OnPressed += _ => OnActivatePressed?.Invoke();
    }

    public void Update(ESPortalGeneratorConsoleBuiState state)
    {
        StatusLabel.UnsafeSetMarkup(state.Charge >= 1
            ? Loc.GetString("es-ui-portalgen-console-label-status-ready")
            : state.Charging
                ? Loc.GetString("es-ui-portalgen-console-label-status-charging")
                : Loc.GetString("es-ui-portalgen-console-label-status-nopower"));

        ActivateButton.Disabled = state.Charge < 1 || state.ThreatsLeft > 0;

        ChargeLabel.UnsafeSetMarkup(Loc.GetString("es-ui-portalgen-console-label-charge-fmt",
            ("charge", (int) (state.Charge * 100))));

        ThreatsLeftLabel.UnsafeSetMarkup(Loc.GetString("es-ui-portalgen-console-label-status-stillthreats",
            ("threats", state.ThreatsLeft)));

        ChargeBar.Value = state.Charge;
        ResearchBar.Value = (float) state.CurrentResearchStage / state.MaxResearchStage;
    }
}
